### PR TITLE
Python 3.8

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Comment by leofang** [comment]
Thanks for help @mrakitin, and sorry for my delayed reply. Our GPU machine was under stress test, so I brought it offline from Azure in the past few days. It's now back online and has completed all tests. But, we'll still need its resource recently, and due to the long test times (1.5-2 hr per test, and we have 3 (PY version) * 4 (CUDA version) = 12 tests...) I'm going to disable the tests for now, otherwise when merging to the master all these will be rerun.

**Comment by leofang** [comment]
Commended out the tests. Will skip CI and merge right away.

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
Thanks again, Maksim!

**Comment by leofang** [comment]
btw I will check back to ensure only PY38 packages are uploaded. As we didn't bump the build number, other Python versions should complain a package already exists on Anaconda.

**Comment by mrakitin** [comment]
Ah, I see. I was surprised why the builds take so long. Now it's clear. And yes, that should only build Python 3.8 packages as we didn't bump the build number.

**Comment by leofang** [comment]
Something is wrong, @mrakitin. Non-PY38 packages are being uploaded as well...Not a big deal for this repo, but we should try to find out the reason when we have time.
截圖 2020-07-08 上午12 16 43

**Comment by leofang** [comment]
I think the hash is changed for some reason, so it is recognized as a new build..

**Pull request merged**
